datasource:
  username: root
  password: 12341234
  driver-class-name: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/be_commerce_1?useUnicode=true&characterEncoding=UTF-8

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


